default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bibliothecaire
  password: u7tRf64bo

development:
  <<: *default
  database: bibliotheque_dev

production:
  <<: *default
  database: bibliotheque_dev

